const SUPABASE_URL='https://cwjeisgyrjjevifgunsx.supabase.co';
const SUPABASE_KEY='sb_publishable_0UscdZysDJyUvH5HMnE3-g_lzvx0dB9';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY),CFG=window.RIEN_CONFIG||{};
const quotes=["Le vide est plein de possibilités.","Aujourd'hui, j'ai décidé de ne rien décider.","Le RIEN n'est pas un manque, c'est un luxe.","Ne rien faire, mais le faire bien.","La productivité est en pause. Le style, jamais.","Mon agenda est rempli d'espaces libres."];
const badges=[['10','Débutant du RIEN',10],['50','Maître du vide',50],['🔥','Série prestigieuse',100],['👑','Souverain du RIEN',250]];
const key='rien-v4';let state=Object.assign({personalCount:0,worldCount:7254631,streak:1,weeklyCount:0,monthlyCount:0,likedQuotes:[],headlineQuote:"Ne rien faire, c'est déjà faire quelque chose."},JSON.parse(localStorage.getItem(key)||'{}')),user=null,profile=null,selectedPlan='monthly',communityMode='create';
const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('fr-FR').format(Number(n||0)),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(){localStorage.setItem(key,JSON.stringify(state))}
function render(){['personalCount','statsTotalCount'].forEach(id=>$(id).textContent=fmt(state.personalCount));$('worldCount').textContent=fmt(state.worldCount);$('streakCount').textContent=state.streak;$('weeklyCount').textContent=fmt(state.weeklyCount);$('monthlyCount').textContent=fmt(state.monthlyCount);$('headlineQuote').textContent=`« ${state.headlineQuote} »`;renderQuotes();renderBadges()}
function renderQuotes(){const el=$('quoteList');el.innerHTML='';quotes.forEach(q=>{const a=document.createElement('article');a.className='quote-card';a.innerHTML=`<p>${esc(q)}</p><button class="quote-like">${state.likedQuotes.includes(q)?'♥':'♡'}</button>`;a.querySelector('button').onclick=()=>{state.likedQuotes=state.likedQuotes.includes(q)?state.likedQuotes.filter(x=>x!==q):[...state.likedQuotes,q];save();renderQuotes()};el.append(a)})}
function renderBadges(){const b=$('badges'),g=$('badgeGoals');b.innerHTML='';g.innerHTML='';badges.forEach(([emoji,title,goal])=>{const ok=state.personalCount>=goal,p=Math.min(100,Math.round(state.personalCount/goal*100));b.insertAdjacentHTML('beforeend',`<article class="badge-chip"><div class="emoji">${emoji}</div><strong>${title}</strong><small>${ok?'Débloqué':'Verrouillé'}</small></article>`);g.insertAdjacentHTML('beforeend',`<article class="goal"><div class="goal-top"><div><strong>${title}</strong><br><small>Faire RIEN ${goal} fois</small></div><strong>${Math.min(state.personalCount,goal)}/${goal}</strong></div><div class="progress"><span style="width:${p}%"></span></div></article>`)} )}
function go(t){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen-${t}`));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.target===t));scrollTo({top:0,behavior:'smooth'});if(t==='community')loadCommunity()}
async function loadWorld(){const {data}=await db.from('rien_global_stats').select('total_count').eq('singleton',1).maybeSingle();if(data){state.worldCount=Number(data.total_count);save();render()}}
async function loadAccount(){const {data:{session}}=await db.auth.getSession();user=session?.user||null;if(!user){profile=null;renderAccount();renderGuestCommunity();await loadWorld();handleIncoming();return}await db.rpc('rien_ensure_user');const [{data:p},{data:s}]=await Promise.all([db.from('rien_profiles').select('*').eq('user_id',user.id).maybeSingle(),db.from('rien_user_stats').select('*').eq('user_id',user.id).maybeSingle()]);profile=p;if(s){state.personalCount=+s.total_count;state.streak=+s.streak;state.weeklyCount=+s.weekly_count;state.monthlyCount=+s.monthly_count}renderAccount();render();await Promise.all([loadWorld(),loadCommunity()]);handleIncoming()}
function renderAccount(){if(user){$('accountButton').textContent=profile?.display_name||user.email.split('@')[0];$('verifiedBadge').classList.toggle('hidden',!user.email_confirmed_at);$('logoutButton').classList.remove('hidden');$('communityUserName').textContent=profile?.display_name||'Utilisateur';$('communityAvatar').textContent=profile?.avatar_initial||'R';$('communityHint').textContent=profile?.is_premium?'Membre RIEN Premium':'Compte vérifié • Communauté active'}else{$('accountButton').textContent='Créer un compte';$('verifiedBadge').classList.add('hidden');$('logoutButton').classList.add('hidden');$('communityUserName').textContent='Anonyme du RIEN';$('communityAvatar').textContent='R';$('communityHint').textContent='Connecte-toi pour rejoindre le vide collectif.'}}
async function press(){state.headlineQuote=quotes[Math.floor(Math.random()*quotes.length)];$('message').textContent=['Bravo. Tu viens de faire RIEN. Encore.','Exécution inutile validée.','Aucun problème résolu. Excellent.','Pause prestigieuse enregistrée.'][Math.floor(Math.random()*4)];if(user){const {data,error}=await db.rpc('rien_increment');if(!error&&data?.[0]){state.personalCount=+data[0].user_total;state.worldCount=+data[0].world_total;state.streak=+data[0].user_streak;state.weeklyCount++;state.monthlyCount++}}else{state.personalCount++;state.weeklyCount++;state.monthlyCount++;$('message').textContent='RIEN local enregistré. Crée un compte pour rejoindre le monde.'}save();render();navigator.vibrate?.(18);if(state.personalCount&&state.personalCount%10===0)openShare()}
function authMode(mode){const signup=mode==='signup';$('signupFields').classList.toggle('hidden',!signup);$('confirmPasswordLabel').classList.toggle('hidden',!signup);$('termsLabel').classList.toggle('hidden',!signup);$('signupButton').classList.toggle('hidden',!signup);$('loginButton').textContent=signup?'J’ai déjà un compte':'Se connecter';$('loginButton').dataset.mode=signup?'switch':'login'}
function openAuth(mode='signup'){$('authMessage').textContent='';authMode(mode);$('authDialog').showModal()}
async function signUp(){const name=$('displayNameInput').value.trim(),email=$('emailInput').value.trim().toLowerCase(),pw=$('passwordInput').value,confirm=$('confirmPasswordInput').value;if(name.length<3)return $('authMessage').textContent='Pseudo : 3 caractères minimum.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return $('authMessage').textContent='Adresse email invalide.';if(pw.length<8||!/[A-Za-z]/.test(pw)||!\d/.test(pw))return $('authMessage').textContent='Mot de passe : 8 caractères, avec lettre et chiffre.';if(pw!==confirm)return $('authMessage').textContent='Les mots de passe ne correspondent pas.';if(!$('termsInput').checked)return $('authMessage').textContent='Accepte les conditions pour continuer.';$('authMessage').textContent='Création et envoi de la validation…';const {data,error}=await db.auth.signUp({email,password:pw,options:{data:{display_name:name},emailRedirectTo:location.origin+location.pathname}});if(error)return $('authMessage').textContent=error.message;$('resendButton').classList.remove('hidden');$('authMessage').textContent=data.session?'Compte créé et connecté.':'Compte créé. Valide maintenant ton email via le message reçu.';if(data.session)setTimeout(()=>{$('authDialog').close();loadAccount()},400)}
async function signIn(){const email=$('emailInput').value.trim().toLowerCase(),password=$('passwordInput').value;$('authMessage').textContent='Connexion…';const {error}=await db.auth.signInWithPassword({email,password});if(error)return $('authMessage').textContent=error.message.includes('Email not confirmed')?'Email non validé. Consulte ta boîte mail.':error.message;$('authMessage').textContent='Connexion validée.';setTimeout(()=>{$('authDialog').close();loadAccount()},300)}
async function resend(){const email=$('emailInput').value.trim().toLowerCase();const {error}=await db.auth.resend({type:'signup',email,options:{emailRedirectTo:location.origin+location.pathname}});$('authMessage').textContent=error?error.message:'Email de validation renvoyé.'}
async function signOut(){await db.auth.signOut();user=profile=null;$('authDialog').close();renderAccount();renderGuestCommunity()}
function inviteUrl(){return profile?.invite_code?`${location.origin}${location.pathname}?invite=${profile.invite_code}`:location.href}
function communityUrl(code){return `${location.origin}${location.pathname}?community=${code}`}
function openShare(text=`J’ai fait RIEN ${state.personalCount} fois sur RIEN™. Viens ne rien faire avec moi.`,url=inviteUrl()){$('sharePreviewText').textContent=text;$('shareDialog').dataset.text=text;$('shareDialog').dataset.url=url;$('shareDialog').showModal()}
async function nativeShare(text,url){try{if(navigator.share){await navigator.share({title:'RIEN™',text,url});return true}}catch{}return false}
async function shareNetwork(net){const text=$('shareDialog').dataset.text,url=$('shareDialog').dataset.url,payload=`${text} ${url}`;if(net==='whatsapp')return window.open(`https://wa.me/?text=${encodeURIComponent(payload)}`,'_blank');if(net==='facebook')return window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`,'_blank');if(net==='copy'){await navigator.clipboard.writeText(payload);return alert('Lien copié.')}if(['instagram','story','tiktok','native'].includes(net)){if(!(await nativeShare(text,url))){await navigator.clipboard.writeText(payload);alert('Lien copié. Ouvre ensuite ton réseau social pour le partager.')}}}
async function loadCommunity(){if(!user)return renderGuestCommunity();const {data:m=[]}=await db.from('rien_community_members').select('community_id,role').eq('user_id',user.id),ids=m.map(x=>x.community_id);let cs=[];if(ids.length)({data:cs=[]}=await db.from('rien_communities').select('*').in('community_id',ids).order('created_at',{ascending:false}));$('communityCount').textContent=cs.length;$('communitiesList').innerHTML='';cs.forEach(c=>{const r=document.createElement('article');r.className='community-card';r.innerHTML=`<div class="avatar">${esc(c.name[0].toUpperCase())}</div><div><strong>${esc(c.name)}</strong><small>${esc(c.description||'Communauté du RIEN')}</small></div><button class="chip">Partager</button>`;r.querySelector('button').onclick=()=>openShare(`Rejoins « ${c.name} » sur RIEN™.`,communityUrl(c.invite_code));$('communitiesList').append(r)});if(!cs.length)$('communitiesList').innerHTML='<article class="community-card"><div><strong>Aucune communauté</strong><small>Crée la première.</small></div></article>';await Promise.all([loadFriends(),loadPosts()])}
function renderGuestCommunity(){$('communityCount').textContent='0';$('communitiesList').innerHTML='<article class="community-card"><div><strong>Connexion requise</strong><small>Crée un compte vérifié pour créer ou rejoindre une communauté.</small></div></article>';$('friendsList').innerHTML='';$('feedList').innerHTML=''}
async function loadFriends(){const {data:rels=[]}=await db.from('rien_friendships').select('*').or(`requester_id.eq.${user.id},addressee_id.eq.${user.id}`).order('created_at',{ascending:false}),ids=[...new Set(rels.flatMap(r=>[r.requester_id,r.addressee_id]).filter(id=>id!==user.id))];let ps=[],ss=[];if(ids.length){({data:ps=[]}=await db.from('rien_profiles').select('user_id,display_name,avatar_initial').in('user_id',ids));({data:ss=[]}=await db.from('rien_user_stats').select('user_id,total_count,streak').in('user_id',ids))}const pm=Object.fromEntries(ps.map(p=>[p.user_id,p])),sm=Object.fromEntries(ss.map(s=>[s.user_id,s])),el=$('friendsList');el.innerHTML='';rels.filter(r=>r.status==='pending'&&r.addressee_id===user.id).forEach(r=>{const p=pm[r.requester_id]||{display_name:'Utilisateur',avatar_initial:'R'},row=document.createElement('article');row.className='friend-card';row.innerHTML=`<div class="avatar">${esc(p.avatar_initial)}</div><div><strong>${esc(p.display_name)}</strong><small>Veut ne rien faire avec toi</small></div><button class="chip">Accepter</button>`;row.querySelector('button').onclick=async()=>{await db.from('rien_friendships').update({status:'accepted'}).eq('friendship_id',r.friendship_id);loadFriends()};el.append(row)});rels.filter(r=>r.status==='accepted').forEach(r=>{const id=r.requester_id===user.id?r.addressee_id:r.requester_id,p=pm[id]||{display_name:'Utilisateur',avatar_initial:'R'},s=sm[id]||{total_count:0,streak:1};el.insertAdjacentHTML('beforeend',`<article class="friend-card"><div class="avatar">${esc(p.avatar_initial)}</div><div><strong>${esc(p.display_name)}</strong><small>${fmt(s.total_count)} RIEN • série ${s.streak} j</small></div></article>`)});if(!el.children.length)el.innerHTML='<article class="friend-card"><div><strong>Pas encore d’amis</strong><small>Partage ton lien personnel.</small></div></article>'}
async function loadPosts(){const {data:posts=[]}=await db.from('rien_posts').select('*').order('created_at',{ascending:false}).limit(25),ids=[...new Set(posts.map(p=>p.user_id))];let ps=[];if(ids.length)({data:ps=[]}=await db.from('rien_profiles').select('user_id,display_name,avatar_initial').in('user_id',ids));const pm=Object.fromEntries(ps.map(p=>[p.user_id,p])),el=$('feedList');el.innerHTML='';posts.forEach(post=>{const p=pm[post.user_id]||{display_name:'Anonyme',avatar_initial:'R'};el.insertAdjacentHTML('beforeend',`<article class="feed-item"><div class="avatar">${esc(p.avatar_initial)}</div><div><strong>${esc(p.display_name)}</strong><p>${esc(post.body)}</p></div></article>`)});if(!posts.length)el.innerHTML='<p>Le mur est vide. Très cohérent.</p>'}
async function postNothing(){if(!user)return openAuth();const body=prompt('Publie quelque chose d’inutile.',`Je viens de faire RIEN ${state.personalCount} fois.`);if(!body)return;await db.from('rien_posts').insert({user_id:user.id,body:body.trim().slice(0,280)});loadPosts()}
function openCommunity(mode){if(!user)return openAuth();communityMode=mode;const create=mode==='create';$('communityDialogTitle').textContent=create?'Créer une communauté':'Rejoindre une communauté';$('communityCreateFields').classList.toggle('hidden',!create);$('communityCodeLabel').classList.toggle('hidden',create);$('communitySubmitButton').textContent=create?'Créer':'Rejoindre';$('communityMessage').textContent='';$('communityDialog').showModal()}
async function submitCommunity(e){e.preventDefault();if(communityMode==='create'){const name=$('communityNameInput').value.trim(),desc=$('communityDescriptionInput').value.trim();if(name.length<2)return $('communityMessage').textContent='Nom trop court.';const {data,error}=await db.rpc('rien_create_community',{p_name:name,p_description:desc});if(error)return $('communityMessage').textContent=error.message;$('communityDialog').close();await loadCommunity();openShare(`Rejoins « ${data.name} » sur RIEN™.`,communityUrl(data.invite_code))}else{const code=$('communityCodeInput').value.trim().toUpperCase(),{data,error}=await db.rpc('rien_join_community',{p_invite_code:code});if(error)return $('communityMessage').textContent='Code invalide.';$('communityDialog').close();await loadCommunity();alert(`Tu as rejoint ${data.name}.`)}}
async function addFriend(){if(!user)return openAuth();const code=prompt('Code d’invitation de ton ami ?');if(!code)return;const {error}=await db.rpc('rien_friend_by_invite',{p_invite_code:code.trim().toUpperCase()});alert(error?'Code invalide ou invitation déjà existante.':'Invitation envoyée.');loadFriends()}
async function handleIncoming(){const q=new URLSearchParams(location.search),f=q.get('invite'),c=q.get('community');if(!f&&!c)return;if(!user){$('message').textContent='Invitation détectée. Connecte-toi pour la valider.';openAuth();return}if(f)await db.rpc('rien_friend_by_invite',{p_invite_code:f});if(c)await db.rpc('rien_join_community',{p_invite_code:c});history.replaceState({},'',location.pathname);go('community');loadCommunity()}
function checkout(){const link=CFG.paymentLinks?.[selectedPlan];if(link)return location.href=link;$('paymentNote').textContent='La boutique est prête, mais aucun compte marchand n’est encore relié. Ajoute un lien Stripe/PayPal dans config.js pour encaisser réellement.'}
function initAds(){const a=CFG.ads||{};if(!a.clientId||!a.slotId)return;const s=document.createElement('script');s.async=true;s.crossOrigin='anonymous';s.src=`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${a.clientId}`;document.head.appendChild(s);$('adPlaceholder').innerHTML=`<ins class="adsbygoogle" style="display:block" data-ad-client="${esc(a.clientId)}" data-ad-slot="${esc(a.slotId)}" data-ad-format="auto" data-full-width-responsive="true"></ins>`;s.onload=()=>{(window.adsbygoogle=window.adsbygoogle||[]).push({})}}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>go(n.dataset.target));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('nothingButton').onclick=press;$('heroShareButton').onclick=()=>openShare();$('shareStatsButton').onclick=()=>openShare(`Mon compteur RIEN™ : ${state.personalCount} actions inutiles, série ${state.streak} jours.`);$('accountButton').onclick=()=>openAuth(user?'login':'signup');$('closeAuthButton').onclick=()=>$('authDialog').close();$('signupButton').onclick=signUp;$('loginButton').onclick=()=>$('loginButton').dataset.mode==='switch'?authMode('login'):signIn();$('resendButton').onclick=resend;$('logoutButton').onclick=signOut;$('inviteButton').onclick=()=>user?openShare('Rejoins-moi sur RIEN™.',inviteUrl()):openAuth();$('createCommunityButton').onclick=()=>openCommunity('create');$('joinCommunityButton').onclick=()=>openCommunity('join');$('closeCommunityDialog').onclick=()=>$('communityDialog').close();$('communityForm').onsubmit=submitCommunity;$('addFriendButton').onclick=addFriend;$('postNothingButton').onclick=postNothing;$('closeShareButton').onclick=()=>$('shareDialog').close();$('nativeShareButton').onclick=()=>shareNetwork('native');document.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>shareNetwork(b.dataset.share));document.querySelectorAll('.plan-card').forEach(b=>b.onclick=()=>{selectedPlan=b.dataset.plan;document.querySelectorAll('.plan-card').forEach(x=>x.classList.toggle('selected',x===b))});$('checkoutButton').onclick=checkout;db.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;setTimeout(loadAccount,0)});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();renderGuestCommunity();initAds();loadAccount();