const SUPABASE_URL='https://cwjeisgyrjjevifgunsx.supabase.co';
const SUPABASE_KEY='sb_publishable_0UscdZysDJyUvH5HMnE3-g_lzvx0dB9';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const localKey='rien-local-v3';
const quotes=["Le vide est plein de possibilités.","Aujourd'hui, j'ai décidé de ne rien décider.","Le RIEN n'est pas un manque, c'est un luxe.","Ne rien faire, mais le faire bien.","La productivité est en pause. Le style, jamais.","Mon agenda est rempli d'espaces libres.","Le silence aussi mérite un compteur.","Rien n'avance, et c'est très reposant."];
const badgeDefs=[{emoji:'10',title:'Débutant',subtitle:'du RIEN',goal:10},{emoji:'50',title:'Maître',subtitle:'du vide',goal:50},{emoji:'🔥',title:'Série 7',subtitle:'jours',goal:70},{emoji:'👑',title:'Souverain',subtitle:'du RIEN',goal:150}];
const defaultLocal={personalCount:0,worldCount:7254631,streak:1,weeklyCount:0,monthlyCount:0,likedQuotes:[],headlineQuote:"Ne rien faire, c'est déjà faire quelque chose.",theme:'default'};
let state=loadLocal(),sound=false,currentTheme=state.theme||'default',sessionUser=null,currentProfile=null;
const $=id=>document.getElementById(id);const screens=document.querySelectorAll('.screen'),nav=document.querySelectorAll('.nav-item');
function loadLocal(){try{return {...defaultLocal,...JSON.parse(localStorage.getItem(localKey)||'{}')}}catch{return {...defaultLocal}}}
function saveLocal(){localStorage.setItem(localKey,JSON.stringify(state))}
function fmt(n){return new Intl.NumberFormat('fr-FR').format(Number(n||0))}
function setMessage(text){$('message').textContent=text}
function renderCounters(){$('personalCount').textContent=fmt(state.personalCount);$('worldCount').textContent=fmt(state.worldCount);$('streakCount').textContent=state.streak;$('statsTotalCount').textContent=fmt(state.personalCount);$('weeklyCount').textContent=fmt(state.weeklyCount);$('monthlyCount').textContent=fmt(state.monthlyCount);$('headlineQuote').textContent=`« ${state.headlineQuote} »`}
function renderQuotes(){const el=$('quoteList');el.innerHTML='';quotes.slice(0,6).forEach(q=>{const a=document.createElement('article');a.className='quote-card';a.innerHTML=`<p>${q}</p><button class="quote-like">${state.likedQuotes.includes(q)?'♥':'♡'}</button>`;a.querySelector('button').onclick=()=>{state.likedQuotes=state.likedQuotes.includes(q)?state.likedQuotes.filter(x=>x!==q):[...state.likedQuotes,q];saveLocal();renderQuotes()};el.appendChild(a)})}
function renderBadges(){const b=$('badges'),g=$('badgeGoals');b.innerHTML='';g.innerHTML='';badgeDefs.forEach(x=>{const i=document.createElement('article');i.className='badge-chip';i.innerHTML=`<div class="emoji">${x.emoji}</div><strong>${x.title}</strong><span>${x.subtitle}</span>`;b.appendChild(i);const row=document.createElement('div');row.className='goal-item';row.innerHTML=`<div><strong>${x.title}</strong><small>Faire RIEN ${x.goal} fois</small></div><strong>${Math.min(state.personalCount,x.goal)}/${x.goal}</strong>`;g.appendChild(row)})}
function render(){renderCounters();renderQuotes();renderBadges()}
async function loadWorld(){const {data}=await db.from('rien_global_stats').select('total_count').eq('singleton',1).maybeSingle();if(data){state.worldCount=Number(data.total_count);saveLocal();renderCounters()}}
async function loadAccount(){const {data:{session}}=await db.auth.getSession();sessionUser=session?.user||null;if(!sessionUser){currentProfile=null;renderAccount();await loadWorld();renderGuestCommunity();return}await db.rpc('rien_ensure_user');const [{data:profile},{data:stats}]=await Promise.all([db.from('rien_profiles').select('*').eq('user_id',sessionUser.id).maybeSingle(),db.from('rien_user_stats').select('*').eq('user_id',sessionUser.id).maybeSingle()]);currentProfile=profile||null;if(stats){state.personalCount=Number(stats.total_count);state.streak=Number(stats.streak);state.weeklyCount=Number(stats.weekly_count);state.monthlyCount=Number(stats.monthly_count)}renderAccount();render();await Promise.all([loadWorld(),loadCommunity()])}
function renderAccount(){const btn=$('accountButton');if(sessionUser){btn.textContent=currentProfile?.display_name||sessionUser.email.split('@')[0];$('logoutButton').classList.remove('hidden');$('loginButton').classList.add('hidden');$('signupButton').classList.add('hidden');$('communityHint').textContent='Ton compteur, tes amis et le mur sont synchronisés.'}else{btn.textContent='Se connecter';$('logoutButton').classList.add('hidden');$('loginButton').classList.remove('hidden');$('signupButton').classList.remove('hidden');$('communityHint').textContent='Connecte-toi pour retrouver une vraie communauté partagée.'}}
async function press(){state.headlineQuote=quotes[Math.floor(Math.random()*quotes.length)];setMessage(["Bravo. Tu viens de faire RIEN. Encore.","Exécution inutile validée.","Aucun problème n'a été résolu, mais c'était élégant.","Pause prestigieuse enregistrée.","Tu excelles dans la non-action."][Math.floor(Math.random()*5)]);if(sessionUser){const {data,error}=await db.rpc('rien_increment');if(!error&&data?.[0]){state.personalCount=Number(data[0].user_total);state.worldCount=Number(data[0].world_total);state.streak=Number(data[0].user_streak);state.weeklyCount++;state.monthlyCount++}else{setMessage('Le RIEN connecté a trébuché. Réessaie.')}}else{state.personalCount++;state.weeklyCount++;state.monthlyCount++;setMessage('RIEN local enregistré. Connecte-toi pour rejoindre le compteur mondial.')}if(navigator.vibrate)navigator.vibrate(20);if(sound)tone();saveLocal();render()}
async function signUp(){const email=$('emailInput').value.trim(),password=$('passwordInput').value,name=$('displayNameInput').value.trim()||'Anonyme du RIEN';$('authMessage').textContent='Création du compte…';const {data,error}=await db.auth.signUp({email,password,options:{data:{display_name:name}}});if(error){$('authMessage').textContent=error.message;return}$('authMessage').textContent=data.session?'Compte créé et connecté.':'Compte créé. Vérifie ton email si une confirmation est demandée.';if(data.session){setTimeout(()=>{$('authDialog').close();loadAccount()},400)}}
async function signIn(){const email=$('emailInput').value.trim(),password=$('passwordInput').value;$('authMessage').textContent='Connexion…';const {error}=await db.auth.signInWithPassword({email,password});if(error){$('authMessage').textContent=error.message;return}$('authMessage').textContent='Connecté.';setTimeout(()=>{$('authDialog').close();loadAccount()},250)}
async function signOut(){await db.auth.signOut();sessionUser=null;currentProfile=null;$('authDialog').close();setMessage('Déconnecté. Ton RIEN local reste ici.');renderAccount();renderGuestCommunity();await loadWorld()}
async function loadCommunity(){if(!sessionUser)return renderGuestCommunity();const {data:rels}=await db.from('rien_friendships').select('*').or(`requester_id.eq.${sessionUser.id},addressee_id.eq.${sessionUser.id}`).order('created_at',{ascending:false});const relationships=rels||[];const ids=[...new Set(relationships.flatMap(r=>[r.requester_id,r.addressee_id]).filter(id=>id!==sessionUser.id))];let profiles=[];if(ids.length){const {data}=await db.from('rien_profiles').select('user_id,display_name,avatar_initial').in('user_id',ids);profiles=data||[]}const profileMap=Object.fromEntries(profiles.map(p=>[p.user_id,p]));let stats=[];if(ids.length){const {data}=await db.from('rien_user_stats').select('user_id,total_count,streak').in('user_id',ids);stats=data||[]}const statMap=Object.fromEntries(stats.map(s=>[s.user_id,s]));const el=$('friendsList');el.innerHTML='';const incoming=relationships.filter(r=>r.status==='pending'&&r.addressee_id===sessionUser.id);incoming.forEach(r=>{const p=profileMap[r.requester_id]||{display_name:'Utilisateur',avatar_initial:'R'};const card=document.createElement('div');card.className='friend-card';card.innerHTML=`<div class="friend-main"><div class="avatar">${p.avatar_initial}</div><div class="friend-meta"><strong>${p.display_name}</strong><small>demande à rejoindre ton RIEN</small></div></div><button class="chip-button">Accepter</button>`;card.querySelector('button').onclick=async()=>{await db.from('rien_friendships').update({status:'accepted'}).eq('friendship_id',r.friendship_id);loadCommunity()};el.appendChild(card)});relationships.filter(r=>r.status==='accepted').forEach(r=>{const other=r.requester_id===sessionUser.id?r.addressee_id:r.requester_id,p=profileMap[other]||{display_name:'Utilisateur',avatar_initial:'R'},s=statMap[other]||{total_count:0,streak:1};const card=document.createElement('div');card.className='friend-card';card.innerHTML=`<div class="friend-main"><div class="avatar">${p.avatar_initial}</div><div class="friend-meta"><strong>${p.display_name}</strong><small>${s.streak} jours de série</small></div></div><div class="friend-score"><strong>${fmt(s.total_count)}</strong><small>RIEN</small></div>`;el.appendChild(card)});if(!el.children.length)el.innerHTML='<p>Aucun ami pour le moment. Le vide est disponible.</p>';await loadPosts()}
async function addFriend(){if(!sessionUser)return openAuth();const name=prompt('Pseudo exact de ton ami du RIEN ?');if(!name)return;const {data,error}=await db.from('rien_profiles').select('user_id,display_name').ilike('display_name',name).neq('user_id',sessionUser.id).limit(1).maybeSingle();if(error||!data){alert('Aucun utilisateur trouvé avec ce pseudo.');return}const {error:insertError}=await db.from('rien_friendships').insert({requester_id:sessionUser.id,addressee_id:data.user_id});if(insertError){alert(insertError.code==='23505'?'Une demande existe déjà.':insertError.message);return}alert(`Invitation envoyée à ${data.display_name}.`);loadCommunity()}
async function loadPosts(){const {data:posts}=await db.from('rien_posts').select('*').order('created_at',{ascending:false}).limit(20);const list=posts||[],ids=[...new Set(list.map(p=>p.user_id))];let profiles=[];if(ids.length){const {data}=await db.from('rien_profiles').select('user_id,display_name,avatar_initial').in('user_id',ids);profiles=data||[]}const pm=Object.fromEntries(profiles.map(p=>[p.user_id,p]));const el=$('feedList');el.innerHTML='';list.forEach(post=>{const p=pm[post.user_id]||{display_name:'Anonyme',avatar_initial:'R'},row=document.createElement('div');row.className='feed-item';row.innerHTML=`<div class="avatar">${p.avatar_initial}</div><div><strong>${p.display_name}</strong><p>${escapeHtml(post.body)}</p></div>`;el.appendChild(row)});if(!list.length)el.innerHTML='<p>Le mur est vide. C’est presque parfait.</p>'}
async function postNothing(){if(!sessionUser)return openAuth();const body=prompt('Ta publication inutile (280 caractères max) ?',`Je viens de faire RIEN ${state.personalCount} fois et j'en suis fier.`);if(!body)return;const clean=body.trim().slice(0,280);const {error}=await db.from('rien_posts').insert({user_id:sessionUser.id,body:clean});if(error){alert(error.message);return}await loadPosts();openShare(clean)}
function renderGuestCommunity(){$('friendsList').innerHTML='<p>Connecte-toi pour ajouter des amis.</p>';$('feedList').innerHTML='<p>Le mur communautaire apparaît après connexion.</p>'}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function go(target){screens.forEach(s=>s.classList.toggle('active',s.id===`screen-${target}`));nav.forEach(n=>n.classList.toggle('active',n.dataset.target===target));if(target==='communaute'&&sessionUser)loadCommunity()}
function shareText(){return `J'ai fait RIEN ${state.personalCount} fois aujourd'hui sur RIEN™. Qui me rejoint ?`}
function openShare(text=shareText()){const d=$('shareDialog');$('sharePreviewText').textContent=text;d.dataset.shareText=text;d.showModal?d.showModal():share(text)}
async function share(text=$('shareDialog').dataset.shareText||shareText()){try{if(navigator.share)await navigator.share({title:'RIEN™',text,url:location.href});else{await navigator.clipboard.writeText(`${text} ${location.href}`);alert('Texte copié.')}}catch{}try{$('shareDialog').close()}catch{}}
function openAuth(){$('authMessage').textContent=sessionUser?'Tu es connecté.':'';$('authDialog').showModal()}
function tone(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=392;g.gain.value=.03;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.08)}
function cycleTheme(){currentTheme=currentTheme==='default'?'nebula':currentTheme==='nebula'?'midnight':'default';state.theme=currentTheme;const r=document.documentElement;if(currentTheme==='nebula'){r.style.setProperty('--violet','#ac6cff');r.style.setProperty('--violet2','#ef72ff');r.style.setProperty('--blue','#7bd6ff')}else if(currentTheme==='midnight'){r.style.setProperty('--violet','#5a71ff');r.style.setProperty('--violet2','#8fc1ff');r.style.setProperty('--blue','#5cf0d6')}else{r.style.setProperty('--violet','#8d55ff');r.style.setProperty('--violet2','#be63ff');r.style.setProperty('--blue','#68b7ff')}saveLocal()}
$('nothingButton').onclick=press;$('accountButton').onclick=openAuth;$('loginButton').onclick=signIn;$('signupButton').onclick=signUp;$('logoutButton').onclick=signOut;$('closeAuthButton').onclick=()=>$('authDialog').close();$('soundToggle').onclick=()=>{sound=!sound;$('soundToggle').textContent=sound?'●':'◌'};$('themeToggle').onclick=cycleTheme;$('newQuoteButton').onclick=()=>{state.headlineQuote=quotes[Math.floor(Math.random()*quotes.length)];saveLocal();render()};$('shareStatsButton').onclick=()=>openShare(`J'ai fait RIEN ${state.personalCount} fois avec une série de ${state.streak} jours sur RIEN™.`);$('nativeShareButton').onclick=e=>{e.preventDefault();share()};$('inviteButton').onclick=()=>openShare(`Rejoins ma communauté RIEN™ : ${location.href}`);$('addFriendButton').onclick=addFriend;$('postNothingButton').onclick=postNothing;nav.forEach(n=>n.onclick=()=>go(n.dataset.target));document.querySelectorAll('.back-ghost').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('.social-btn').forEach(b=>b.onclick=()=>openShare(`J'ai fait RIEN ${state.personalCount} fois sur RIEN™. Partage depuis ${b.dataset.network} ?`));
db.auth.onAuthStateChange((_event,session)=>{sessionUser=session?.user||null;setTimeout(loadAccount,0)});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();renderGuestCommunity();cycleTheme();loadAccount();