const storageKey='rien-app-state-v3';
const quotes=["Le vide est plein de possibilités.","Aujourd'hui, j'ai décidé de ne rien décider.","Le RIEN n'est pas un manque, c'est un luxe.","Ne rien faire, mais le faire bien.","La productivité est en pause. Le style, jamais.","Mon agenda est rempli d'espaces libres.","Le silence aussi mérite un compteur.","Rien n'avance, et c'est très reposant."];
const badges=[{emoji:'10',title:'Débutant',subtitle:'du RIEN',goal:10},{emoji:'50',title:'Maître',subtitle:'du vide',goal:50},{emoji:'🔥',title:'Série 7',subtitle:'jours',goal:70},{emoji:'👑',title:'Souverain',subtitle:'du RIEN',goal:150}];
const defaults={personalCount:0,worldCount:7254631,streak:1,weeklyCount:0,monthlyCount:0,likedQuotes:[],lastDay:new Date().toDateString(),headlineQuote:"Ne rien faire, c'est déjà faire quelque chose.",theme:'default',friends:[{name:'Léo',initials:'L',count:64,streak:7,status:'actif'},{name:'Maya',initials:'M',count:42,streak:4,status:'zen'},{name:'Noa',initials:'N',count:118,streak:12,status:'rienologue'}],feed:[{author:'Léo',text:'vient de faire RIEN 8 fois avant le café.'},{author:'Maya',text:'a partagé une phrase du RIEN sur sa story.'},{author:'Noa',text:'défie le groupe à atteindre 300 RIEN aujourd’hui.'}]};
let state=loadState(),sound=false,currentTheme=state.theme||'default';
const $=id=>document.getElementById(id);
const screens=document.querySelectorAll('.screen'),nav=document.querySelectorAll('.nav-item');
function loadState(){try{return {...defaults,...JSON.parse(localStorage.getItem(storageKey)||'{}')}}catch{return {...defaults}}}
function save(){localStorage.setItem(storageKey,JSON.stringify(state))}
function freshDay(){const t=new Date().toDateString();if(state.lastDay!==t){state.streak++;state.lastDay=t;save()}}
function fmt(n){return new Intl.NumberFormat('fr-FR').format(n)}
function render(){
 $('personalCount').textContent=state.personalCount;$('worldCount').textContent=fmt(state.worldCount);$('streakCount').textContent=state.streak;$('statsTotalCount').textContent=state.personalCount;$('weeklyCount').textContent=state.weeklyCount;$('monthlyCount').textContent=state.monthlyCount;$('headlineQuote').textContent=`« ${state.headlineQuote} »`;renderQuotes();renderBadges();renderFriends();renderFeed();
}
function press(){state.personalCount++;state.worldCount+=1+Math.floor(Math.random()*3);state.weeklyCount++;state.monthlyCount++;state.headlineQuote=quotes[Math.floor(Math.random()*quotes.length)];$('message').textContent=["Bravo. Tu viens de faire RIEN. Encore.","Exécution inutile validée.","Aucun problème n'a été résolu, mais c'était élégant.","Pause prestigieuse enregistrée.","Tu excelles dans la non-action."][Math.floor(Math.random()*5)];if(navigator.vibrate)navigator.vibrate(20);if(sound)tone();save();render()}
function renderQuotes(){const el=$('quoteList');el.innerHTML='';quotes.slice(0,6).forEach(q=>{const a=document.createElement('article');a.className='quote-card';a.innerHTML=`<p>${q}</p><button class="quote-like">${state.likedQuotes.includes(q)?'♥':'♡'}</button>`;a.querySelector('button').onclick=()=>{state.likedQuotes=state.likedQuotes.includes(q)?state.likedQuotes.filter(x=>x!==q):[...state.likedQuotes,q];save();renderQuotes()};el.appendChild(a)})}
function renderBadges(){const b=$('badges'),g=$('badgeGoals');b.innerHTML='';g.innerHTML='';badges.forEach(x=>{const i=document.createElement('article');i.className='badge-chip';i.innerHTML=`<div class="emoji">${x.emoji}</div><strong>${x.title}</strong><span>${x.subtitle}</span>`;b.appendChild(i);const row=document.createElement('div');row.className='goal-item';row.innerHTML=`<div><strong>${x.title}</strong><small>Faire RIEN ${x.goal} fois</small></div><strong>${Math.min(state.personalCount,x.goal)}/${x.goal}</strong>`;g.appendChild(row)})}
function renderFriends(){const el=$('friendsList');el.innerHTML='';state.friends.forEach(f=>{const d=document.createElement('div');d.className='friend-card';d.innerHTML=`<div class="friend-main"><div class="avatar">${f.initials}</div><div class="friend-meta"><strong>${f.name}</strong><small>${f.streak} jours · ${f.status}</small></div></div><div class="friend-score"><strong>${f.count}</strong><small>RIEN</small></div>`;el.appendChild(d)})}
function renderFeed(){const el=$('feedList');el.innerHTML='';state.feed.slice(0,6).forEach(p=>{const d=document.createElement('div');d.className='feed-item';d.innerHTML=`<div class="avatar">${p.author[0].toUpperCase()}</div><div><strong>${p.author}</strong><p>${p.text}</p></div>`;el.appendChild(d)})}
function go(target){screens.forEach(s=>s.classList.toggle('active',s.id===`screen-${target}`));nav.forEach(n=>n.classList.toggle('active',n.dataset.target===target))}
function shareText(){return `J'ai fait RIEN ${state.personalCount} fois aujourd'hui sur RIEN™. Qui me rejoint ?`}
function openShare(text=shareText()){const d=$('shareDialog');$('sharePreviewText').textContent=text;d.dataset.shareText=text;d.showModal?d.showModal():share(text)}
async function share(text=$('shareDialog').dataset.shareText||shareText()){try{if(navigator.share)await navigator.share({title:'RIEN™',text,url:location.href});else{await navigator.clipboard.writeText(`${text} ${location.href}`);alert('Texte copié.')}}catch{}try{$('shareDialog').close()}catch{}}
function tone(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=392;g.gain.value=.03;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.08)}
function theme(){currentTheme=currentTheme==='default'?'nebula':currentTheme==='nebula'?'midnight':'default';state.theme=currentTheme;const r=document.documentElement;if(currentTheme==='nebula'){r.style.setProperty('--violet','#ac6cff');r.style.setProperty('--violet2','#ef72ff');r.style.setProperty('--blue','#7bd6ff')}else if(currentTheme==='midnight'){r.style.setProperty('--violet','#5a71ff');r.style.setProperty('--violet2','#8fc1ff');r.style.setProperty('--blue','#5cf0d6')}else{r.style.setProperty('--violet','#8d55ff');r.style.setProperty('--violet2','#be63ff');r.style.setProperty('--blue','#68b7ff')}save()}
$('nothingButton').onclick=press;$('soundToggle').onclick=()=>{sound=!sound;$('soundToggle').textContent=sound?'●':'◌'};$('themeToggle').onclick=theme;$('newQuoteButton').onclick=()=>{state.headlineQuote=quotes[Math.floor(Math.random()*quotes.length)];save();render()};$('shareStatsButton').onclick=()=>openShare(`J'ai fait RIEN ${state.personalCount} fois avec une série de ${state.streak} jours sur RIEN™.`);$('nativeShareButton').onclick=e=>{e.preventDefault();share()};$('inviteButton').onclick=()=>openShare(`Rejoins ma communauté RIEN™ : ${location.href}`);$('addFriendButton').onclick=()=>{const name=prompt('Nom de ton ami du RIEN ?');if(name){state.friends.unshift({name,initials:name.trim()[0].toUpperCase(),count:0,streak:1,status:'nouveau'});save();renderFriends()}};$('postNothingButton').onclick=()=>{state.feed.unshift({author:'Toi',text:`vient de faire RIEN ${state.personalCount} fois et en est fier.`});save();renderFeed();openShare()};
nav.forEach(n=>n.onclick=()=>go(n.dataset.target));document.querySelectorAll('.back-ghost').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('.social-btn').forEach(b=>b.onclick=()=>openShare(`J'ai fait RIEN ${state.personalCount} fois sur RIEN™. Partage depuis ${b.dataset.network} ?`));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});freshDay();theme();render();